/*
Copyright © 2026 Godwin Mafireyi <mafireyi@gmail.com>
*/
package cmd

import (
	"fmt"
	"log"
	"os"

	"github.com/gmaffy/genome-whisperer/annotation"
	"github.com/spf13/cobra"
)

// AddGeneDescriptionsCmd represents the AddGeneDescriptions command
var AddGeneDescriptionsCmd = &cobra.Command{
	Use:   "AddGeneDescriptions",
	Short: "Add gene descriptions to a vcf file, generated by snpEff",
	Long:  `Add gene descriptions to a vcf file, generated by snpEff using a gene description tsv file with 2 columns: gene_id, gene_description`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Adding gene descriptions to vcf files ................")
		vcfs, vErr := cmd.Flags().GetStringSlice("variant")
		if vErr != nil {
			fmt.Println("Error getting variant flag")
		}
		descFile, dErr := cmd.Flags().GetString("gene-description-tsv")
		if dErr != nil {
			fmt.Println("Error getting gene-description flag")
		}
		bsaseq, bErr := cmd.Flags().GetBool("bsaseq")
		if bErr != nil {
			fmt.Println("Error getting bsaseq flag")
		}
		//fmt.Println(bsaseq)
		//fmt.Println(vcfs)
		//fmt.Println(descFile)
		if descFile == "" {
			fmt.Println("Please provide a gene description TSV with --gene-description-tsv")
			return
		}
		if len(vcfs) == 0 {
			fmt.Println("Please provide at least one vcf file")
			return
		}
		for i := range vcfs {
			_, err := os.Stat(vcfs[i])
			if err != nil {
				fmt.Printf("Vcf file: %s is not a valid file path", vcfs[i])
				log.Fatal(err)
			}
		}

		err, _ := annotation.AddDescriptions(vcfs, descFile, bsaseq)
		if err != nil {
			fmt.Println(err)
			return
		}
		//fmt.Printf("Descriptions added to variant Files %s. Created: %s\n---------------------\n", vcfs, descSnpEffTsvs)

	},
}

func init() {
	rootCmd.AddCommand(AddGeneDescriptionsCmd)
	AddGeneDescriptionsCmd.Flags().SortFlags = false
	AddGeneDescriptionsCmd.Flags().StringSliceP("variant", "V", []string{}, "Path to a VCF/variant file (repeatable)")
	if err := AddGeneDescriptionsCmd.MarkFlagRequired("variant"); err != nil {
		return
	}
}
