/*
Copyright © 2026 Godwin Mafireyi <mafireyi@gmail.com>
*/
package cmd

import (
	"fmt"
	"log"
	"os"

	"github.com/gmaffy/genome-whisperer/annotation"
	"github.com/spf13/cobra"
)

// AddGeneDescriptionsCmd represents the AddGeneDescriptions command
var AddGeneDescriptionsCmd = &cobra.Command{
	Use:   "AddGeneDescriptions",
	Short: "Add gene descriptions to a vcf file, generated by snpEff",
	Long:  `Add gene descriptions to a vcf file, generated by snpEff using a gene description tsv file with 2 columns: gene_id, gene_description`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("Adding gene descriptions to vcf files ................")
		vcfs, vErr := cmd.Flags().GetStringSlice("variant")
		if vErr != nil {
			fmt.Println("Error getting variant flag")
		}
		descFile, dErr := cmd.Flags().GetString("gene-description-tsv")
		if dErr != nil {
			fmt.Println("Error getting gene-description flag")
		}
		bsaseq, bErr := cmd.Flags().GetBool("bsaseq")
		if bErr != nil {
			fmt.Println("Error getting bsaseq flag")
		}
		//fmt.Println(bsaseq)
		//fmt.Println(vcfs)
		//fmt.Println(descFile)
		if descFile == "" {
			fmt.Println("Please provide gene-description-tsv name with flag -g ")
			return
		}
		if len(vcfs) == 0 {
			fmt.Println("Please provide at least one vcf file")
			return
		}
		for i := range vcfs {
			_, err := os.Stat(vcfs[i])
			if err != nil {
				fmt.Printf("Vcf file: %s is not a valid file path", vcfs[i])
				log.Fatal(err)
			}
		}

		err, _ := annotation.AddDescriptions(vcfs, descFile, bsaseq)
		if err != nil {
			fmt.Println(err)
			return
		}
		//fmt.Printf("Descriptions added to variant Files %s. Created: %s\n---------------------\n", vcfs, descSnpEffTsvs)

	},
}

func init() {
	rootCmd.AddCommand(AddGeneDescriptionsCmd)

	// Here you will define your flags and configuration settings.

	// Cobra supports Persistent Flags which will work for this command
	// and all subcommands, e.g.:
	// AddGeneDescriptionsCmd.PersistentFlags().String("foo", "", "A help for foo")

	// Cobra supports local flags which will only run when this command
	// is called directly, e.g.:
	AddGeneDescriptionsCmd.Flags().StringSliceP("variant", "V", []string{}, "snpEff tsv file ...")
	AddGeneDescriptionsCmd.Flags().StringP("gene-description-tsv", "g", "", "gene description tsv file ...")
	AddGeneDescriptionsCmd.Flags().Bool("bsaseq", false, "bsaseq output")

}
